### ISSUE TITLE
No module named 'cached_property'

### ISSUE THREAD

**Issue by YerongLi** [jicewarwick/AShareData#2]
请问这个**cached_property**是怎么来的呢？简单setup之后tests里面的文件需要这个依赖。谢谢！

     $ python A_share_data_update_routine.py 
      Traceback (most recent call last):
        File "A_share_data_update_routine.py", line 4, in <module>
          from AShareData import ConstLimitStockFactorCompositor, MySQLInterface, prepare_engine, TushareData, WindData
        File "<frozen zipimport>", line 259, in load_module
        File "/home/yerong/local/Python3/lib/python3.8/site-packages/AShareData-0.1.0-py3.8.egg/AShareData/__init__.py", line 4, in <module>
        File "<frozen zipimport>", line 259, in load_module
        File "/home/yerong/local/Python3/lib/python3.8/site-packages/AShareData-0.1.0-py3.8.egg/AShareData/AShareDataReader.py", line 3, in <module>
      ModuleNotFoundError: No module named 'cached_property'

      $ python factor_test.py 
      Traceback (most recent call last):
        File "factor_test.py", line 3, in <module>
          from AShareData.DBInterface import MySQLInterface, prepare_engine
        File "<frozen zipimport>", line 259, in load_module
        File "/home/yerong/local/Python3/lib/python3.8/site-packages/AShareData-0.1.0-py3.8.egg/AShareData/__init__.py", line 4, in <module>
        File "<frozen zipimport>", line 259, in load_module
        File "/home/yerong/local/Python3/lib/python3.8/site-packages/AShareData-0.1.0-py3.8.egg/AShareData/AShareDataReader.py", line 3, in <module>
      ModuleNotFoundError: No module named 'cached_property'

**Comment by wentixiaogege** [comment]
这是版本不对，作者没说具体的版本，python3.8，对应的其他版本不一样。。。
